services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: fcg-mongo-notifications
    ports:
      - "27017:27017"
    volumes:
      - mongodata_notifications:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  notifications-api:
    build: .
    ports:
      - "8084:8080"
    environment:
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      Mongo__ConnectionString: "mongodb://mongo:27017"
      Mongo__Database: "fcg_notifications"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy

volumes:
  mongodata_notifications:
